version: '3.8'

services:
  # Backend Service Configuration
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # The backend will be available at http://backend:8000 from the frontend container
      - BACKEND_URL=http://backend:8000

  # Frontend Service Configuration
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      # Pass the backend URL to the Streamlit app
      - API_URL=http://backend:8000
    depends_on:
      - backend