services:
  # A Web Service for the FastAPI backend
  - type: web
    name: ml-backend
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /

  # A Web Service for the Streamlit frontend
  - type: web
    name: ml-frontend
    env: docker
    rootDir: frontend
    plan: free
    envVars:
      - key: API_URL
        value: http://ml-backend:8000 # This is the corrected line
